### PR TITLE
Come fli with me

### PR DESCRIPTION
**Pull request by 0xModene**
# **Pull Request Template**

###### _Select a category that relates to the content of your pull request (choose all that apply)._

- [ ] Bug Fix
- [ ] Content
- [ ] New Feature
- [ ] Documentation
- [ ] Code Refactoring

&nbsp;

###### _Provide a brief summary of the changes you made and their purpose as they relate to Index UI. <br/>If applicable, please link the corresponding issue number._

&nbsp;

### **Fixes: Issue #**

&nbsp;

###### _Include proof that your changes function properly and resolve the linked issue._

&nbsp;

###### _By submitting this pull request, you are confirming the following to be true:_

- I have reviewed the [Contribution Guidelines](https://github.com/SetProtocol/index-ui/blob/master/CONTRIBUTING.md).
- I have performed a self-review of my own code.
- I have updated my repository to match the master at `SetProtocol/index-ui`.
- I have included test data or screenshots that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by janndriessen — APPROVED** [review]
LGTM!

Only thing I found is that the data for allocations (e.g. Aave Matic Market USDC in Inverse MATIC Flexible Leverage Index) doesn't seem to be shown correctly e.g. no logos. Addresses seem to be correct. Maybe the tokens are missing in tokenlists?

**Comment by 0xModene** [comment]
> Aave Matic Market USDC

I've added amUSDC, amWETH, and amWMATIC to the tokenlist library and updated this PR to have the updated tokenlist

**Comment by janndriessen** [comment]
I forgot earlier +1 for the title 🤣 👍

**Comment by 0xModene** [comment]
If you can use some exotic booze, there's a bar in far Bombay

**Pull request merged**
